# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: no-commit-to-branch
        name: don't commit to main branch
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        name: check for large source and project files
        exclude_types: [binary, csv]
      - id: check-added-large-files
        name: check for large test files
        args: ['--maxkb=10000']
      - id: detect-private-key
      - id: check-yaml
      - id: check-xml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.12.0
    hooks:
      - id: eslint
